### ISSUE TITLE
Looks like it's skipping creating events using old space-time parameters

### ISSUE THREAD

**Issue by admahood** [earthlab/firedpy#13]
So, when I loop through different space-time combinations, it checks for already-classified events in the ~/proj/tables/events/ folder. e.g.:

h06v03 event table exists, skipping...
h07v03 event table exists, skipping...
h08v03 event table exists, skipping...
h09v02 event table exists, skipping...
h09v03 event table exists, skipping...
h10v02 event table exists, skipping...
h10v03 event table exists, skipping...
h11v02 event table exists, skipping...
h11v03 event table exists, skipping...
h12v02 event table exists, skipping...
h13v02 event table exists, skipping...

But when I'm creating different spacetime combos I don't want that, so in my loop i have to manually delete the contents of that folder. There should probably be a naming convention change for those files too, where the space and time parameters are added into those names, OR just remove the code where it checks if these files exists already.

**Comment by maxwellCcook** [comment]
I am looking at this now - along with resolving the "tile not found" error.
