### ISSUE TITLE
edge case process is not right

### ISSUE THREAD

**Issue by admahood** [earthlab/firedpy#16]
it uses polygons instead of using ST thresholds on the points

**Comment by admahood** [comment]
![edge_fail](https://user-images.githubusercontent.com/7245247/92964353-3059fc80-f431-11ea-8c97-fb45993f7c4f.png)

**Comment by admahood** [comment]
So, doing the western hemisphere, it's chugging a ton of ram, and taking like 8 hours to do the edge cases. So not only is the edge case processes incorrect theoretically, it's also a memory/resource bottleneck.

**Comment by maxwellCcook** [comment]
Dang. So yeah that is a bigger issue than just the theoretical aspect. You think using the buildEvents() function will help that? I'll do more testing to see if I can get it to work this weekend.

**Comment by admahood** [comment]
Yeah that plus I think there might be some significant reorganization  of that part of the process required...

**Comment by admahood** [comment]
Another detail that's very important: 3 iterations per second for the edge cases, 1000+ iterations per second for normal event building

![edge_times](https://user-images.githubusercontent.com/7245247/93027778-9333cb00-f5cc-11ea-90e2-165d641f8177.png)

**Comment by admahood** [comment]
so, like, the event builder algorithm would reduce that 16 minutes to 2 seconds

**Comment by admahood** [comment]
another view of the edge case slowness, except this time it's with south america (so it includes tropical savannahs) 4 seconds per iterations (instead of iterations per second) - goes as high as 8 seconds

![edge_iterations](https://user-images.githubusercontent.com/7245247/93040979-977dd980-f608-11ea-9173-4114924e16fa.png)

**Comment by maxwellCcook** [comment]
Got it thanks for sharing these. Let's try to tackle this tomorrow during our meeting?...I will have some examples to share but yeah this is def high priority to integrate the eventBuilder() in this step. That is some big memory loss!
