### ISSUE TITLE
lat long for ignition

### ISSUE THREAD

**Issue by admahood** [earthlab/firedpy#20]

**Comment by maxwellCcook** [comment]
lat/long for ignition left in the tables and gpkg outputs

**Comment by maxwellCcook** [comment]
When trying to map the ignition coordinates for CONUS, the points fall out in the Pacific and maintain the sinusoidal shape. I've tried re-projecting and converting coordinates but this issue might be better solved in the code itself.

**Comment by admahood** [comment]
@maxwellCcook I'd say, it's low on the priority list so maybe just comment that section out for now.

**Comment by admahood** [comment]
caculate ignition estimation from raw event table as avg of all x & y occurring on first date
