### ISSUE TITLE
option to specify the output polygon filename?

### ISSUE THREAD

**Issue by admahood** [earthlab/firedpy#30]

**Comment by admahood** [comment]
I think it should just be something super basic like fired_events.gpkg; fired_daily.gpkg; etc. The reason being is that right now for example, I'm trying to do the whole western hemisphere, and it's going to take a while, so I need to pipe the command to copy it out of the container after its done or else my aws instance will shut down and I'll lose everything. Having a simple name makes it a little easier to do things like that

**Comment by maxwellCcook** [comment]
@admahood so leave the default as is but allow users to specify the name?

**Comment by admahood** [comment]
@maxwellCcook I'm thinking just have a base name (e.g. fired) followed by _events.gpkg or _daily.gpkg and that's it. no dates or anything. that makes it easier to have something like this:

firedpy -s 1 -t 5 -file_name bolivia --shapefile && aws s3 cp bolivia_events.gpkg s3://yadayadayada

**Comment by maxwellCcook** [comment]
This is done. Default to "fired_events" or "fired_daily". Not pushed to master yet.

**Comment by maxwellCcook** [comment]
Default as mentioned above - there is an argument to specify the file name as well.
