### ISSUE TITLE
still looking for .nc files for tiles that were skipped due to lack of fires (and errors out)

### ISSUE THREAD

**Issue by admahood** [earthlab/firedpy#31]
No such file or directory: b'/home/firedpy/proj/rasters/burn_area/netcdfs/h03v06.nc'

**Comment by maxwellCcook** [comment]
Thanks for pointing this out. Working on resolving that now and will update you when it's fixed.

**Comment by admahood** [comment]
That might not actually be happening. it think I may have made a mistake to cause that error? maybe a false alarm

**Comment by maxwellCcook** [comment]
I think this may not actually be happening. I have written in the code to check for ".nc" files prior to running. I did some testing and it appears to be working properly.
