### ISSUE TITLE
polygon error

### ISSUE THREAD

**Issue by admahood** [earthlab/firedpy#32]
i built the events for all of north america, but the polygon creation step had an error. I was still able to get the table output which will be enough for my immediate purposes. I'm not familiar enough with the code to understand what that error is pointing to, but it seems like maybe a column name thing?

![polygon_error](https://user-images.githubusercontent.com/7245247/93037765-68636a00-f600-11ea-951d-7b7fdf416f2d.png)

**Comment by maxwellCcook** [comment]
Not sure how this slipped past me and sorry for that. Doing some testing today I was able to recreate the issue and I think it is fixed. Have not pushed yet but will at some point this afternoon.

**Comment by maxwellCcook** [comment]
This is resolved - had to rework column indexing to account for landcover and ecoregion attributes and the error was a result of that testing.
