### ISSUE TITLE
docker image not rebuilding on push

### ISSUE THREAD

**Issue by lwasser** [earthlab/firedpy#37]
@admahood i just updated your branch build in dockerhub to `main` as it was looking for the master branch but the branch name has been changed to main. Can you please push another change so we can test that things kickoff correctly?

**Comment by lwasser** [comment]
i believe it's building your current commit @admahood  . are you  able to see that on dockerhub? 

<img width="1277" alt="Screen Shot 2021-05-20 at 4 09 19 PM" src="https://user-images.githubusercontent.com/7649194/119054993-c57ca000-b985-11eb-84ef-47790bd74895.png">

if things are fixed feel free to close ... if not let us know what is happening!

**Comment by admahood** [comment]
It works correctly now! Thanks Leah!
