### ISSUE TITLE
landcover lookup table not found 

### ISSUE THREAD

**Issue by maxwellCcook** [earthlab/firedpy#41]
@admahood does not appear to happen if the HDF files have already been downloaded (related to working directory). Fixed by copying the appropriate lookup table at the beginning of the workflow based on user input. Will push to master

**Comment by admahood** [comment]
looks like this bug was fixed, but something happened that broke the docker build

**Comment by admahood** [comment]
There appears to be a problem with importing shutil. I googled it and it looks like maybe in anaconda, it's called pytest-shutil. I changed the environment.yaml to that, and in the beginning of __main__.py, I changed it to import pytest-shutil as shutil. Maybe that'll fix it?

**Comment by maxwellCcook** [comment]
@admahood I see that you changed it in _main_.py but then @EllieLindrooth changed it back (likely because the import statement does not work as such. I am testing on Docker now and will close if this is resolved.

**Comment by admahood** [comment]
yeah my guess is that the issue is that shutil is essentially base python, so the shutil in the environment.yaml is unnecessary and is causing the error. I added that pytest-shutil but i'm guessing we can just delete that line and it'll be fine.

**Comment by maxwellCcook** [comment]
I think you are right. Closing this issue for now!
