### ISSUE TITLE
'right_df' should be GeoDataFrame, got <class 'NoneType'>

### ISSUE THREAD

**Issue by EllieLindrooth** [earthlab/firedpy#47]
<img width="570" alt="Screen Shot 2021-06-22 at 11 33 39 AM" src="https://user-images.githubusercontent.com/54689091/122972745-b3f43280-d34d-11eb-9574-3d767f47ba1c.png">

**Comment by maxwellCcook** [comment]
@EllieLindrooth can you paste the firedpy command line you used for this run? Testing now on my end but it might be helpful to know what parameters you used. Thanks!

**Comment by maxwellCcook** [comment]
I see where the error is occurring - for the world ecoregion join. Testing an update now.

**Comment by EllieLindrooth** [comment]
> I see where the error is occurring - for the world ecoregion join. Testing an update now.

I'm still getting the error. There was another file that was missing that I uploaded that I hoped would fix the errors but its sill saying "ValueError: 'right_df' should be GeoDataFrame, got <class 'NoneType'>". The line that is causing the error is "File "/opt/conda/envs/firedpy/lib/python3.7/site-packages/geopandas/tools/sjoin.py", line 40, in sjoin", so I think it's an error in syntax or the sjoin join_right_df tool.

**Comment by EllieLindrooth** [comment]
> > I see where the error is occurring - for the world ecoregion join. Testing an update now.
> 
> I'm still getting the error. There was another file that was missing that I uploaded that I hoped would fix the errors but its sill saying "ValueError: 'right_df' should be GeoDataFrame, got <class 'NoneType'>". The line that is causing the error is "File "/opt/conda/envs/firedpy/lib/python3.7/site-packages/geopandas/tools/sjoin.py", line 40, in sjoin", so I think it's an error in syntax or the sjoin join_right_df tool which is in the geopandas package.
