### ISSUE TITLE
polgons are still not clipping at the end

### ISSUE THREAD

**Issue by admahood** [earthlab/firedpy#51]
![image](https://user-images.githubusercontent.com/7245247/125524324-c2e67313-aa28-47f5-879e-0b5bd420e6a0.png)

For example, this is supposed to be CONUS + Alaska

**Comment by admahood** [comment]
line 1859, functions.py

                    # gdfd = gpd.sjoin(gdfd, shp, how="left", op="intersects")

**Comment by admahood** [comment]
it might actually be a good idea to put like a 200km buffer around the polygon and clip in the beginning too, to cut down on processing time

**Comment by maxwellCcook** [comment]
@admahood update to include extraction of overlapping events is pushed. However, it does this at the end currently. We could build it into earlier stages of the workflow such as when the spatial points are created?

**Comment by maxwellCcook** [comment]
@admahood I suppose overlap should only be considered after the merging of edge events? i.e., we still need to create the event grids for each overlapping HDF event file

**Comment by admahood** [comment]
@maxwellCcook My thinking here is inspired by the case of Bolivia, which sits at the intersection of 4 tiles. There, I ran firedpy, and it took 50GB of RAM and an entire day to process, because the tiles it's on are also covering a big chunk of Brazil. So I ended up producing something like 1,000,000 events, and then clipped away about 800,000 of them. 

If we can do a thing where at the very beginning, after downloading the HDFs but before creating events, where we just turn all the irrelevent pixels to NAs (but still give some space for fires that go into other countries, hence the 100km buffer) then we can cut way down on processing time and RAM for cases like that. So basically I think it would be right in the before building events, just masking each HDF stack, if that makes sense

**Comment by maxwellCcook** [comment]
Fantastic idea! Right now I have it finding the buffered intersection at the "buildPoints()" function and it already cut the processing time for Colorado (with the tiles already downloaded) down by ~5 min! I will work on implementing a mask function whereby the events are only created from the HDF if they fall within the buffer.

**Comment by admahood** [comment]
Also to be clear, my thought is a buffered mask on the beginning, but then
still doing the unbuffered intersect at the end
