### ISSUE TITLE
world ecoregions path error

### ISSUE THREAD

**Issue by admahood** [earthlab/firedpy#52]
![world_ecoregion_error](https://user-images.githubusercontent.com/7245247/126047183-590caf13-22cb-4681-9590-3e1ddfc695a6.png)

**Comment by admahood** [comment]
I'm not sure, but I'm guessing we should do some test runs with the world ecoregions once this is resolve to make sure it's grabbing the ecoregion names correctly, etc

**Comment by admahood** [comment]
line 1814 in functions.py is also pointing to a .gpkg, but then the ref folder has a .shp.

**Comment by EllieLindrooth** [comment]
Just fixed this error, should be working fine
