### ISSUE TITLE
readme does not have exactly correct filenames

### ISSUE THREAD

**Issue by admahood** [earthlab/firedpy#56]
e.g. I created fired_hawaii_to2021121_events.gpkg and it has simply fired_events_hawaii.gpkg in the file list.

**Comment by admahood** [comment]
it also says I have 60 rows and there are 76

**Comment by EllieLindrooth** [comment]
Fixed it!

**Comment by EllieLindrooth** [comment]
I also changed it so that its saved in the ouptuts folder
