### ISSUE TITLE
final intersect is not quite right

### ISSUE THREAD

**Issue by admahood** [earthlab/firedpy#71]
So, the idea I had, and what the algorithm was previously doing, was to filter the final perimeters to those that had at least some area within the AOI polygon. So, something like if polygon is touching == true, then the whole polygon is included. That way when we include the whole event, even it crosses a political boundary. It looks like there is a clip of the points before they are turned into polygons. 

![image](https://user-images.githubusercontent.com/7245247/156437146-72ed6ced-7525-4066-9fda-3320794306cd.png)

**Comment by EllieLindrooth** [comment]
Is this for the daily events?

**Comment by admahood** [comment]
it is the daily! so that's actually not the wyoming border

Here are the events, and those look correct:

![image](https://user-images.githubusercontent.com/7245247/156677643-b256685b-2a63-420d-a9b5-a92748a6b2e8.png)

But then here's the daily:

![image](https://user-images.githubusercontent.com/7245247/156677700-f31d5876-39ce-4df4-821e-76696c6d0138.png)

So it looks like the final intersects thing does not happen for the daily. 

Just a thought, but maybe in the workflow, it might actually make sense to basically just save a vector of id numbers for the final events polygon that gets written out, then just filter by that to save out the daily polygons. That might actually be faster than doing the geometric operation twice.

**Comment by admahood** [comment]
Another thought is that whatever that initial buffer is can probably be cut in half
