### ISSUE TITLE
buildpoints is called twice

### ISSUE THREAD

**Issue by EllieLindrooth** [earthlab/firedpy#79]
buildPoints is called in both buildFireAttributes and buildPolygons. It may make more sense to call it in main and pass the gdf that it returns as an argument to these other functions instead of having to run it twice.

**Comment by EllieLindrooth** [comment]
I realized this does need to be called twice, but I think this is why the points are off by half a pixel. By calling it a second time, it moves the already centered pixel coords another half a pixel

**Comment by admahood** [comment]
One idea is to just add an argument to the build points function, i.e. shift=True, where you can just turn off the half pixel adjustment the second time the function is called
