### ISSUE TITLE
using a shapefile input doesn't work

### ISSUE THREAD

**Issue by admahood** [earthlab/firedpy#8]
Two problems: modis tile grid not found, then if it is found it doesn;t seem to be reprojecting the input shapefile.

I input a shapefile of alaska, and it outputted a file not found for the modis world tile grid. I created this file in the proper directory to see if it would then work, and it outputted an error that seemed to indicate a coordinate reference system problem.

**Comment by maxwellCcook** [comment]
@admahood  can you test the shapefile-update branch? I think this is finally working with any input projection

**Comment by admahood** [comment]
I tried it with a shapefile of just the country of bolivia, and it's still defaulting to h18v08 (somewhere in africa) when it should be h11 and h12, v10

**Comment by admahood** [comment]
feel free to use the same shapefile to see if you get the same results at s3://earthlab-amahood/bolivia.gpkg

**Comment by maxwellCcook** [comment]
I just tested and it with the bolivia.gpkg is working correctly on my machine. It does look like the commit made it to GitHub so I am not sure what might be happening. I could clone a new repository from the shapefile_update branch and see if it still works correctly.
