### ISSUE TITLE
weird bug is now on the docker version

### ISSUE THREAD

**Issue by admahood** [earthlab/firedpy#85]
![image](https://user-images.githubusercontent.com/7245247/200418505-85db4244-5878-4bd8-ba30-c269a12cd474.png)
![image](https://user-images.githubusercontent.com/7245247/200418545-4b0143cd-1ca4-4b78-bdb5-f77c4a08ddec.png)

**Comment by itsamepetros** [comment]
Hey @admahood . Did you figure out how to fix this bug?

**Comment by maxwellCcook** [comment]
Hi @itsamepetros - we have not resolved this bug yet but will be working on it over the next month. We suspect one of the more recent commits introduced the bug so we might even just roll back a couple commits for a very short term fix. Apologies for the inconvenience here.

**Comment by admahood** [comment]
@itsamepetros That bug appears to be resolved.
