### ISSUE TITLE
There was a problem performing the transition projection

### ISSUE THREAD

**Issue by shawnmiaomiao** [earthlab/firedpy#88]
<img width="1210" alt="874f95b7da241715492004dfd177f2d" src="https://github.com/earthlab/firedpy/assets/138224356/77eb766c-3c1f-4b01-bb7c-ce4b3be4b524">

**Comment by admahood** [comment]
hey @shawnmiaomiao , the interface where you just type in firedpy and follow the prompts is still buggy. We just fixed the other method, where you enter in everything in a single command. For your case, you would type in:

firedpy -aoi ref/individual_countries/china.gpkg

If you do that, that should work. 
Cheers,
Adam

**Comment by shawnmiaomiao** [comment]
Thank you for your answer, but I re-installed the code package and tried to run with the whole type, but this bug still occurs, may I ask how to solve it，thank you very much!

**Comment by admahood** [comment]
Hey sorry,
The docker account has changed. It is now earthlabcu/firedpy
